### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by mughu94** [wmcmurray/just-detect-adblock#2]
Hi , i'm just want to say about this plugin isn't working if run the script plugins on Brave browser with Version 0.67.124 . thank you

**Comment by wmcmurray** [comment]
@Carbone13 Thanks for the info, I will check that as soon as I have time ! :)

**Comment by wmcmurray** [comment]
*:hourglass: One year later... lol*

Brave block requests before they can actually append ads to the page, that's why this package was not able to detect it.

But since [this commit](https://github.com/wmcmurray/just-detect-adblock/commit/846dd5239faa3d95b33f2dfa3b390714411b299f) I've implemented checks for both Brave and Opera custom adblockers, It should be available since release `v1.1.0` of this package !

Thanks for the heads up.
